# Generated by Django 3.0.7 on 2023-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='numbers',
            field=models.PositiveIntegerField(blank=True, default='100', null=True),
        ),
    ]
