# Generated by Django 3.0.7 on 2023-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230826_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='cta',
            field=models.CharField(blank=True, default='READ MORE', max_length=50, null=True),
        ),
    ]
