# Generated by Django 3.0.7 on 2023-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Astrologer', 'Astrologer'), ('Customer', 'Customer'), ('Translator', 'Translator')], default='Customer', max_length=15),
        ),
    ]
