# Generated by Django 3.0.7 on 2023-09-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
        ('conversation', '0002_auto_20230917_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='translator',
        ),
        migrations.AddField(
            model_name='conversation',
            name='translator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='translator.Translator'),
        ),
    ]
