# Generated by Django 3.0.7 on 2023-10-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_auto_20230923_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
